spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    druid:
#     连接池初始大小
      initial-size: 5
#     最小空闲连接数
      min-idle: 10
#     最大连接数
      max-active: 20
#     不统计这些数据
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#     访问监控网页的用户名和密码
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
#    数据库索引，默认为0
    database: 0
#    redis host ip
    host: 192.168.56.131
#    redis  连接端口
    port: 6379
#    服务器连接密码（默认为空）
    password:
#    连接超时时间（毫秒）
    timeout: 1000

    jedis:
#      连接池配置
      pool:
#        连接池最大连接数
        max-active: 8
#        连接池最大阻塞等待时间（负值表示没有限制）
        max-wait: -1
#        连接池最大空闲连接
        max-idle: 8
#        连接池最小空闲连接
        min-idle: 0

security:
  jwt:
#   JWT 请求头
    tokenHeader: Authorization
#   秘钥
    securityKey: mall
#   过期时间(60*60*1)
    expiration: 3600
#   设置JWT开头
    tokenHead: 'Bearer'
#   用于生成refreshtoken的秘钥
    refreshSecurityKey: cwh
#   refreshToken过期时间(60*60*24*7)
    refreshTokenExpiration: 604800
#   refreshToken延长过期时间
    extendTime:
  ignored:
    urls:
      - /admin/login
      - /admin/register
#      - /admin/logout
#      - /admin/**
      - /swagger-resources/**
      - /**/v2/api-docs
      - /v3/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/**
      - /swagger-ui/*
      - /swagger/**

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
